title: Projet

status:
  draft: Brouillon
  listed: Publié

columns:
  - width: 2/3  
    fields:
      subtitle:
        label: Sous-titre
        type: text
        width: 3/4
      year:
        label: Année
        type: number
        width: 1/4
      text:
        label: Texte
        type: textarea
        size: medium
      gallery:
        type: files
        label: Galerie
        layout: cards
        info: "{{file.caption}}"
        uploads:
          template: image
  - width: 1/3
    sections:
      data:
        type: fields
        fields:
          cover:
            label: Couverture
            help: Image pour la vignette
            type: files
            max: 1     
      files:
        type: files
        headline: Tous les fichiers