title: Site

columns:
  - width: 2/3
    sections:
      projects:
        extends: sections/projects
  - width: 1/3
    sections:
      pages:
        type: pages
        templates: 
          - home
          - projects
          - about
